### ISSUE TITLE
Update requests dependency

### ISSUE THREAD

**Issue by bro-wi** [viktor-platform/bro#30]
@regbers-viktor @MSlootwegVIKTOR @GliderGeek 

Please update request and also implement #23. Versions of Requests between v2.3.0 and v2.30.0 are vulnerable to potential
forwarding of Proxy-Authorization headers to destination servers whenfollowing HTTPS redirects. : https://github.com/psf/requests/releases/tag/v2.31.0

**Comment by regbers-viktor** [comment]
Should be fixed in v0.2.10
